sudo: required
language: python
python: "3.9"

addons:
  postgresql: "9.6"

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - nvm install 16

install:
  - npm install
  - pip3 install tox

script:
  - psql -c 'create database nostromo_test;' -U postgres
  - psql -c 'create database ripley_loch_test;' -U postgres
  - psql nostromo_test -c 'create role ripley superuser login; alter schema public owner to ripley;' -U postgres
  - psql ripley_loch_test -c 'alter schema public owner to ripley;' -U postgres
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1

services:
  - redis-server
